apply(plugin: "fabric-loom")
apply(plugin: "maven-publish")
apply(plugin: "com.replaymod.preprocess")

int mcVersion = 1


preprocess {
    mcVersion = vars.get().get("MC")
//    tabIndentation.set(false)
}

repositories {
    var github_username  = System.getenv("GITHUB_USERNAME")
    var github_token = System.getenv("GITHUB_TOKEN")

    maven { url = 'https://masa.dy.fi/maven' }
    maven { url = "https://www.cursemaven.com" }
    maven { url = "https://maven.terraformersmc.com/releases" }
    maven { url = "https://maven.kyrptonaught.dev" }
    maven {
        url = "https://api.modrinth.com/maven"
    }

    maven {
        url = "https://mvnrepository.com/artifact/com.belerweb/pinyin4j"
        content {
            includeGroupAndSubgroups("com.belerweb")
        }
    }

    maven {
        name = "BlameJared"
        url = uri("https://maven.blamejared.com")
        content {
            includeGroupAndSubgroups("com.blamejared.searchables")
        }
    }
    maven {
        name = "AlexIIL"
        url = "https://staging.alexiil.uk/maven/"
        content {
            includeGroupAndSubgroups("io.github.cottonmc")
        }
    }

    maven { url = "https://maven.shedaniel.me/" }
    maven {
        name = "jackfredReleases"
        url = mcVersion >= 12106 ? "https://maven.pkg.github.com/ponuing/JackFredLib": "https://maven.jackf.red/releases"
        content {
            includeGroupAndSubgroups("red.jackf")
        }
    }

    // YACL
    maven {
        name = "Xander Maven"
        url = uri("https://maven.isxander.dev/releases")
        content {
			includeGroupAndSubgroups("dev.isxander")
			includeGroupAndSubgroups("org.quiltmc")
		}
    }

    // YACL Snapshots
    maven {
        name = "Xander Snapshot Maven"
        url = uri("https://maven.isxander.dev/snapshots")
		content {
			includeGroupAndSubgroups("dev.isxander")
			includeGroupAndSubgroups("org.quiltmc")
		}
    }


    maven {
        url = "https://jitpack.io"
        content {
            includeGroupAndSubgroups("com.github")
        }
    }

//	maven { url = "https://mvnrepository.com/artifact/com.github.open-android/pinyin4j " }
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}
//  1 = modImplementation 2 = modImplementation include 	3 = modApi	4 = modCompileOnly
// Module, Property prefix, Resolve condition, Transitive depende ncies.
String getYacl() {
//    return "maven.modrinth:yacl";
    return mcVersion == 12002 ? "maven.modrinth:yacl" : "dev.isxander:yet-another-config-lib";
}

String getQuiShulkerBox() {
    String path = mcVersion >= 12101 ? "com.github.MoRanpcy:quickshulker" : "curse.maven:quick-shulker-362669"
    if (mcVersion == 12006) { path = "Haocen2004/quickshulker"}
    return path;
}

def mod_dependencies = [
        ["maven.modrinth:malilib" + ":${project.malilib_version}", 1],
        ["maven.modrinth:item-scroller" + ":${project.item_scrolle_version}", 1],
        ["maven.modrinth:litematica" + ":${project.litematica_version}", 1],
        [getQuiShulkerBox()+":${project.quick_shulker_version}", mcVersion == 12006 ? 6 : 10,"quick_shulker_version","*"],
        ["net.kyrptonaught:kyrptconfig:${project.kyrptconfig_version}", mcVersion >= 12004 ? 0 : 1],
        ["net.kyrptonaught:shulkerutils:${project.shulkerutils_version}", mcVersion >= 12004 ? 0 : 1],
        ["com.terraformersmc:modmenu:${project.modmenu_version}", 1],
        [(mcVersion >= 12006 ? "curse.maven:carpet-349239" : "maven.modrinth:carpet") + ":${project.carpet_version}", 1],
        ["com.blamejared.searchables" + ":${project.searchables}"   , mcVersion >= 12001 ? 1 : 0],
        ["red.jackf.jackfredlib:jackfredlib"+ ":${project.jackfredlib}", mcVersion >= 12001 ? 1 : 0],
        [getYacl() + ":${project.yacl}", mcVersion >= 12001 ? 1 : 0],
        [("maven.modrinth:chest-tracker") + (mcVersion >= 12106 ? "-port" : "") + ":${project.chesttracker}",1],
        [("maven.modrinth:where-is-it" + (mcVersion >= 12106 ? "-port" : "")) + ":${project.whereisit}",1],
        ["maven.modrinth:cloth-config" + ":${project.cloth_config}", mcVersion < 12001 ? 1 : 0],
        ["me.shedaniel.cloth.api:cloth-api" + ":${project.cloth_api}", mcVersion < 11904 ? 1 : 0],
        ["io.github.cottonmc:LibGui" + ":${project.LibGui}", mcVersion < 12001 ? 1 : 0],
]

dependencies {
    //拼音
    implementation include("com.belerweb:pinyin4j:2.5.1")

    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

    implementation 'com.github.jitpack:gradle-simple:1.0'
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation ("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")

//    modImplementation "dev.isxander:yet-another-config-lib:3.6.0+1.21-fabric"
    mod_dependencies.forEach { item ->
        def dependencyNotation = item[0]
        def mode = item[1]
        def idFix = ""
//		if(mode != 0) idFix = "${dependencyNotation}:${project.property("${id}")}"
        if (mode != 0) idFix = dependencyNotation
        if (mode == 1) {
            modImplementation (idFix)
        } else if (mode == 10) {
            modImplementation (idFix){ exclude group: item[3] }
        } else if (mode == 2) {
            modImplementation include(idFix)
        } else if (mode == 3) {
            modApi (idFix)
        } else if (mode == 4) {
            modCompileOnly(idFix)
        } else if (mode == 45) {
            modCompileOnly files(dependencyNotation)
        } else if (mode == 5) {
            modImplementation files(dependencyNotation)
        } else if (mode == 6){
            def file = downloadMod(dependencyNotation, "${project.property("${item[2]}")}")
            if (file == null) return;
            modImplementation files(file)
        }
    }
//	modImplementation "maven.modrinth:jei:${project.jei}"
//	modImplementation "maven.modrinth:carpet-tis-addition:${project.carpet_tis_addition}"

    // Uncomment the following line to enable the deprecated Fabric API modules.
    // These are included in the Fabric API production distribution and allow you to update your mod to the latest modules at a later more convenient time.

    // modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"

    runtimeOnly(project(path: ":fabricWrapper"))
}

def downloadMod(String repo, String version) {
    def libsDir = file('build/libs')
    libsDir.mkdirs()

    // 1. 构造缓存文件名
    def FileName = "${repo.split('/')[1]}"
    // 1. 检查 libs 目录下是否有文件名包含 FileName 的文件
    def existingFile = libsDir.listFiles().find { file ->
        // 不讲武德的mod可能出现大小写不统一的情况
        file.isFile() && file.name.toLowerCase().contains(FileName.toLowerCase())
    }

    // 2. 检查缓存文件是否已存在
    if (existingFile != null) {
        println "缓存命中：${FileName}，跳过下载"
        return existingFile
    }


    repo = repo.split(":")[0]
    def apiUrl = "https://api.github.com/repos/${repo}/releases/tags/${version}"
    def conn = new URL(apiUrl).openConnection() as HttpURLConnection
    conn.setRequestProperty("Accept", "application/vnd.github.v3+json")
    conn.setRequestProperty("User-Agent", "Gradle")

    println(apiUrl)
    def minecraftVersion = "${project.minecraft_version}"
    if (conn.responseCode != 200) {
        return null
    }

    def json = new groovy.json.JsonSlurper().parse(conn.inputStream)
    def assets = json.assets
    // 优先选择文件名包含当前 MC 版本的 jar
    def jarAsset = assets.find {
        it.name.endsWith('.jar') &&
                !it.name.contains('-sources') &&
                it.name.contains(minecraftVersion)
    }

    // 如果找不到匹配版本的，可改为抛出异常或使用第一个非源码 jar
    if (!jarAsset) {
        println "警告：未找到包含 MC 版本" +minecraftVersion+ "的 jar，将使用第一个非源码 jar"
        jarAsset = assets.find { it.name.endsWith('.jar') && !it.name.contains('-sources') }
    }

    if (!jarAsset) throw new GradleException("No jar found")

    def outputFile = new File(libsDir, jarAsset.name)
    if (outputFile.exists()) {
        println "File already exists: ${outputFile.name}, skipping."
        return outputFile
    }

    println "Downloading ${jarAsset.name}..."
    def downloadUrl = jarAsset.browser_download_url
    def downloadConn = new URL(downloadUrl).openConnection() as HttpURLConnection
    downloadConn.setRequestProperty("User-Agent", "Gradle")
    downloadConn.instanceFollowRedirects = true // 自动处理重定向

    downloadConn.inputStream.withStream { input ->
        outputFile.withOutputStream { out ->
            out << input
        }
    }
    println "Downloaded to ${outputFile.absolutePath}"
    return outputFile
}
version = gradle.modVersion
group = project.mod_maven_group

base {
    archivesName.set("${project.mod_archives_base_name}-${project.minecraft_version}")
}

loom {
    interfaceInjection {
        enableDependencyInterfaceInjection.set(true)
    }

    runConfigs.configureEach {
        // Dump modified classes automatically.
        property("mixin.debug.export", "true")
    }

    runConfigs.named("client") {
        programArgs([
                "--width", "1280",
                "--height", "720",
                "--username", "zhaixianyu",
                "--uuid", "a87377da-8bb1-49a0-adc6-0bb8a4863386"
        ])
        runDir("run/client")
    }

    runConfigs.named("server") {
        runDir("run/server")
    }

    runs {
        mixinAuditClient {
            inherit(client)
            vmArgs("-Dmagiclib.mixin_audit=true")
            ideConfigGenerated(false)
            runDir("run/client")
        }

        mixinAuditServer {
            inherit(server)
            vmArgs("-Dmagiclib.mixin_audit=true")
            ideConfigGenerated(false)
            runDir("run/server")
        }
    }

    // Setup client default settings.
    runClient {
        defaultCharacterEncoding("UTF-8")

        if (!new File("${project.project.projectDir}/run/client/options.txt").exists()) {
            new File("${project.projectDir}/run/client").mkdirs()
            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("${project.projectDir}/run/client/options.txt"))
            bufferedWriter.writeLine("autoJump:false")
            bufferedWriter.writeLine("enableVsync:false")
            bufferedWriter.writeLine("forceUnicodeFont:false")
            bufferedWriter.writeLine("fov:0.25")
            bufferedWriter.writeLine("screenEffectScale:1.0")
            bufferedWriter.writeLine("gamma:16.0")
            bufferedWriter.writeLine("guiScale:3")
            bufferedWriter.writeLine("lang:${Locale.getDefault().toString()}")
            bufferedWriter.writeLine("maxFps:260")
            bufferedWriter.writeLine("renderDistance:10")
            bufferedWriter.writeLine("soundCategory_master:0.0")
            bufferedWriter.close()
        }
    }

    // Setup server default settings.
    runServer {
        defaultCharacterEncoding("UTF-8")

        // Agree eula before server init.
        if (!new File("${project.projectDir}/run/server/eula.txt").exists()) {
            new File("${project.projectDir}/run/server").mkdirs()
            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("${project.projectDir}/run/server/eula.txt"))
            bufferedWriter.writeLine("eula=true")
            bufferedWriter.close()
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding("UTF-8")
}

remapJar {
//    remapperIsolation.set(true)
}


def MIXIN_CONFIG_PATHS = ['wuhuclient.mixins.json']
JavaVersion JAVA_COMPATIBILITY
if (mcVersion >= 12005) {
    JAVA_COMPATIBILITY = JavaVersion.VERSION_21
} else if (mcVersion >= 11800) {
    JAVA_COMPATIBILITY = JavaVersion.VERSION_17
} else if (mcVersion >= 11700) {
    JAVA_COMPATIBILITY = JavaVersion.VERSION_16
} else {
    JAVA_COMPATIBILITY = JavaVersion.VERSION_1_8
}
JavaVersion MIXIN_COMPATIBILITY_LEVEL = JAVA_COMPATIBILITY

tasks.withType(JavaCompile).configureEach {
    if (mcVersion >= 12005) {
        it.options.release = 21
    } else if (mcVersion >= 11800) {
        it.options.release = 17
    } else if (mcVersion >= 11700) {
        it.options.release = 16
    } else {
        it.options.release = 8
    }

}

java {

    sourceCompatibility = JAVA_COMPATIBILITY
    targetCompatibility = JAVA_COMPATIBILITY

    withSourcesJar()
}

//jar {
////	from("${rootDir}/LICENSE")
//	from("LICENSE") {
//		rename { "${it}_${project.archivesBaseName}"}
//	}
//}

processResources {
    outputs.upToDateWhen { false }

    from("${rootDir}/LICENSE")

    from("${rootDir}/icon.png") {
        into("assets/${project.mod_id}")
    }

    filesMatching("fabric.mod.json") {
        filter { line ->
            line.trim().startsWith("//") ? null : line
        }

        expand([
                "minecraft_dependency": project.minecraft_dependency,
                "minecraft_version_id": project.minecraft_version.replace(".", "_"),
                "minecraft_version"   : project.minecraft_version,
                "mod_description"     : project.mod_description,
                "mod_homepage"        : project.mod_homepage,
                "mod_id"              : project.mod_id,
                "mod_license"         : project.mod_license,
                "mod_name"            : project.mod_name,
                "mod_sources"         : project.mod_sources,
                "mod_version"         : project.version
        ])
    }

    MIXIN_CONFIG_PATHS.each { mixinConfigPath ->
        filesMatching(mixinConfigPath) {
            filter { s -> s.replace('{{COMPATIBILITY_LEVEL}}', "JAVA_${MIXIN_COMPATIBILITY_LEVEL.ordinal() + 1}") }
        }
    }
}

// configure the maven publication
publishing {
    publications {
        register("mavenJava", MavenPublication) {
            artifactId("${project.mod_id}-${project.minecraft_version.replace(".", "_")}")
            version("${project.minecraft_version}-" + version)
            from(components.java)
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        mavenLocal()

        maven {
            url("$rootDir/publish")
        }
    }
}