# Done to increase the memory available to gradle.
#org.gradle.cache.cleanup=false
org.gradle.jvmargs=-Xmx4G

mod_archives_base_name=WuHuClient
mod_description=Add something interesting <3
mod_homepage=https://space.bilibili.com/31545812
mod_id=wuhuclient
mod_license=LGPLv3
mod_maven_group=com.zxy.wuhu-client
mod_name=WuHu Client
mod_sources=https://github.com/zhaixianyu/wuhu-client
mod_version=1.0.5

loader_version=0.19.3
