minecraft_dependency= >=26.1
#https://fabricmc.net/develop/
minecraft_version=26.1
# Fabric API
fabric_version=0.145.1+26.1

#https://modrinth.com/mod/malilib/versions
malilib_version=0.28.6
#https://modrinth.com/mod/item-scroller/versions
item_scrolle_version=0.31.4
#https://modrinth.com/mod/litematica/versions
litematica_version=0.27.6
#https://jitpack.io/#MoRanpcy/quickshulker
quick_shulker_version=3.0.0-26.1
#https://www.modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.8
#https://modrinth.com/mod/carpet/versions
#https://www.curseforge.com/minecraft/mc-mods/carpet/files/all
carpet_version=7708191

#https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
jackfredlib=0.10.6+26.1
#https://modrinth.com/mod/chest-tracker/versions
chesttracker=2.8.1+26.1
#https://modrinth.com/mod/where-is-it/versions?l=fabric
whereisit=2.7.3+26.1
#https://modrinth.com/mod/searchables/versions?l=fabric
searchables=Searchables-fabric-26.1:1.0.4
#https://modrinth.com/mod/yacl/versions?l=fabric
yacl=3.9.2+26.1-fabric
#https://modrinth.com/mod/modmenu/versions

cloth_config=6
cloth_api=6
LibGui=6
kyrptconfig_version=1.4.6-1.18
shulkerutils_version=1.0.4-1.18