minecraft_dependency=1.21.4

#https://fabricmc.net/develop/
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8

# Fabric API
fabric_version=0.118.0+1.21.4

#https://modrinth.com/mod/malilib/versions
malilib_version=0.23.5
#https://modrinth.com/mod/item-scroller/versions
item_scrolle_version=0.26.5
#https://modrinth.com/mod/litematica/versions
litematica_version=0.21.6
#https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker_version=4592296
kyrptconfig_version=1.4.6-1.18
shulkerutils_version=1.0.4-1.18
#https://www.modrinth.com/mod/modmenu/versions
modmenu_version=13.0.2
#https://modrinth.com/mod/carpet/versions
#https://www.curseforge.com/minecraft/mc-mods/carpet/files/all
carpet_version=5960519

#https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
jackfredlib=0.10.6+1.21.4
#https://modrinth.com/mod/chest-tracker/versions
chesttracker=2.6.7+1.21.4
#https://modrinth.com/mod/where-is-it/versions?l=fabric
whereisit=2.6.4+1.21.2
#https://modrinth.com/mod/searchables/versions?l=fabric
searchables=Searchables-fabric-1.21.4:1.0.3
#https://modrinth.com/mod/yacl/versions?l=fabric
yacl=3.6.2+1.21.4-fabric
#https://modrinth.com/mod/modmenu/versions

cloth_config=6
cloth_api=6
LibGui=6
