minecraft_dependency=>=1.21 <=1.21.1

#https://fabricmc.net/develop/

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
# Fabric API
fabric_version=0.110.0+1.21.1

#https://modrinth.com/mod/malilib/versions
malilib_version=0.21.10
#https://www.curseforge.com/minecraft/mc-mods/item-scroller/files/all
#https://modrinth.com/mod/item-scroller/versions
item_scrolle_version=0.24.60
#https://www.curseforge.com/minecraft/mc-mods/litematica/files/all
#https://modrinth.com/mod/litematica/versions
litematica_version=0.19.61
#https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker_version=2.0.3-1.21.1
#https://www.modrinth.com/mod/modmenu/versions
modmenu_version=11.0.1
#https://modrinth.com/mod/carpet/versions
#https://www.curseforge.com/minecraft/mc-mods/carpet/files/all
carpet_version=5425253

#https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
jackfredlib=0.10.2+1.21.1
#https://modrinth.com/mod/chest-tracker/versions
chesttracker=2.6.5+1.21.1
#https://modrinth.com/mod/where-is-it/versions?l=fabric
whereisit=2.6.3+1.21.1
#https://modrinth.com/mod/searchables/versions?l=fabric
searchables=Searchables-fabric-1.21.1:1.0.2
#https://modrinth.com/mod/yacl/versions?l=fabric
yacl=3.5.0+1.21-fabric
#https://modrinth.com/mod/modmenu/versions

cloth_config=6
cloth_api=6
LibGui=6
kyrptconfig_version=1.4.6-1.18
shulkerutils_version=1.0.4-1.18